
name: course_action

env:
  SHA: "${{github.sha}}"

on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
    - name: print hello
      run: echo "Hello"
      
    - name: print version of ubuntu
      run: lsb_release -a
      
    - name: print sha of commit
      run: echo "${{env.SHA}}"
      
  job2:
    runs-on: ubuntu-latest
  
    steps:
    - name: print all files in repo
      run: ls
      
    - name: run test.sh
      run: bash test.sh
