
name: course_action

env:
  SHA: "${{github.sha}}"
  FIRST_NAME: "Amir"
  

on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
    - name: Print hello
      run: echo "Hello"
      
    - name: Print version of ubuntu
      run: lsb_release -a
      
    - name: Print sha of commit
      run: echo "${{env.SHA}}"
      
  job2:
    runs-on: ubuntu-latest
  
    steps:
    - name: Git clone
      uses: actions/checkout@v1
      
    - name: Print all files in repo
      run: ls -la
      
    - name: Run test.sh
      run: bash test.sh
      
  job3:
    runs-on: ubuntu-latest
  
    steps:
      
    - name: Print first name
      run: echo "First name is ${{env.FIRST_NAME}}"
      
    - name: Print last name
      run: echo "Last name is $LAST_NAME"
      env:
        LAST_NAME: "hOREV"
        
    - name: Print phone with secret
      run: |
        if [ "${{secrets.PHONE_SEC}}" == "123456" ]; then
          echo "Phone number is 0548321321"
        else
          echo "secret invalid"
        fi
